export const ROUTES = {
	ROOT: "/",
	EXPENSES: "/expenses",
	STOCKS: "/stocks",
	CATEGORIES: "/categories",
	CATEGORIE: "/categorie/:id",
	ADDCATEGORIE: "/categorie/add",
	EDITCATEGORIE: "/categorie/edit/:id",
	GOALS: "/goals",
	GOAL: "/goal/:id",
	ADDGOAL: "/goals/add",
	EDITGOAL: "/goals/edit/:id",
	LOGIN: "/login",
	PROFILE: "/profile",
};
